version: "3.8"

services:
  mongo:
    image: mongo
    container_name: pageturn-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/public:/app/public
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
